name: Release

on:
  release:
    types: [published]
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: workshop-upload
        uses: weilbyte/steam-workshop-upload@v1
        with: 
          appid: 294100
          itemid: 1463057070
          path: 'dist'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }}
